version: '3.8'

services:
  app:
    build: .
    container_name: roman-numeral-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: ["npm", "start"]
