openapi: "3.0.0"
info:
  title: "Roman Numeral API"
  version: "1.0.0"
servers:
  - url: "https://aem-production.up.railway.app"
    description: "Production Server"
paths:
  /romannumeral:
    get:
      summary: "Convert numbers to Roman numerals"
      description: "Converts an integer (1-3999) into its Roman numeral representation."
      parameters:
        - name: "query"
          in: "query"
          required: true
          schema:
            type: "integer"
            minimum: 1
            maximum: 3999
      responses:
        "200":
          description: "Successfully converted number to Roman numeral"
          content:
            application/json:
              schema:
                type: object
                properties:
                  input:
                    type: string
                    example: "23"
                  output:
                    type: string
                    example: "XXIII"
