global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "aem_api"
    static_configs:
      - targets: ["aem-production.up.railway.app:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
